Entity/Restaurants.php
<?php

namespace CMS\RestaurantsBundle\Entity;

use CMS\GeoBundle\Entity\Geoobjects;
use CMS\LocalizationBundle\Entity\Cities;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Restaurants
 */
class Restaurants
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $title;

    /**
     * @var Cities
     */
    private $city;

    /**
     * @var string
     */
    private $address;

    /**
     * @var Geoobjects
     */
    private $location;

    /**
     * @var integer
     */
    private $busy_hours_start;

    /**
     * @var integer
     */
    private $busy_hours_end;

    /**
     * @var array
     */
    private $days_off;

    /**
     * @var Kitchens
     */
    private $kitchens;

    /**
     * @var string
     */
    private $descriptions;

    /**
     * @var Images
     */
    private $photos;

    /**
     * @var integer
     */
    private $status = 0;

    /**
     * @var boolean
     */
    private $is_published;

    /**
     * @var boolean
     */
    private $is_deleted;

    /**
     * @var \DateTime
     */
    private $date_create;

    /**
     * @var \DateTime
     */
    private $date_update;

    /**
     * @var integer
     */
    private $create_by;

    /**
     * @var integer
     */
    private $update_by;

    public function __construct()
    {
        $this->photos = new ArrayCollection();
        $this->kitchens = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Restaurants
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @return ArrayCollection
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param ArrayCollection $city
     * @return $this
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @param string $address
     * @return $this
     */
    public function setAddress($address)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * @return Geoobjects
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * @param Geoobjects $location
     * @return $this
     */
    public function setLocation($location)
    {
        $this->location = $location;

        return $this;
    }

    /**
     * @return int
     */
    public function getBusyHoursStart()
    {
        return $this->busy_hours_start;
    }

    /**
     * @param int $busy_hours_start
     * @return $this
     */
    public function setBusyHoursStart($busy_hours_start)
    {
        $this->busy_hours_start = $busy_hours_start;

        return $this;
    }

    /**
     * @return int
     */
    public function getBusyHoursEnd()
    {
        return $this->busy_hours_end;
    }

    /**
     * @param int $busy_hours_end
     * @return $this
     */
    public function setBusyHoursEnd($busy_hours_end)
    {
        $this->busy_hours_end = $busy_hours_end;

        return $this;
    }

    /**
     * @return array
     */
    public function getDaysOff()
    {
        return $this->days_off;
    }

    /**
     * @param array $days_off
     * @return $this
     */
    public function setDaysOff($days_off)
    {
        $this->days_off = $days_off;

        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getKitchens()
    {
        return $this->kitchens;
    }

    /**
     * @param ArrayCollection $kitchens
     * @return $this
     */
    public function setKitchens($kitchens)
    {
        $this->kitchens = $kitchens;

        return $this;
    }

    /**
     * @return string
     */
    public function getDescriptions()
    {
        return $this->descriptions;
    }

    /**
     * @param string $descriptions
     * @return $this
     */
    public function setDescriptions($descriptions)
    {
        $this->descriptions = $descriptions;

        return $this;
    }

    /**
     * @return Images
     */
    public function getPhotos()
    {
        return $this->photos;
    }

    /**
     * @param Images $photos
     * @return $this
     */
    public function setPhotos($photos)
    {
        $this->photos = $photos;

        return $this;
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param int $status
     * @return $this
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return boolean
     */
    public function getIsPublished()
    {
        return $this->is_published;
    }

    /**
     * @param boolean $is_published
     * @return $this
     */
    public function setIsPublished($is_published)
    {
        $this->is_published = $is_published;

        return $this;
    }

    /**
     * @return boolean
     */
    public function getIsDeleted()
    {
        return $this->is_deleted;
    }

    /**
     * @param boolean $is_deleted
     * @return $this
     */
    public function setIsDeleted($is_deleted)
    {
        $this->is_deleted = $is_deleted;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateCreate()
    {
        return $this->date_create;
    }

    /**
     * @param \DateTime $date_create
     * @return $this
     */
    public function setDateCreate($date_create)
    {
        $this->date_create = new \DateTime();

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateUpdate()
    {
        return $this->date_update;
    }

    /**
     * @param \DateTime $date_update
     * @return $this
     */
    public function setDateUpdate($date_update)
    {
        $this->date_update = new \DateTime();

        return $this;
    }

    /**
     * @return int
     */
    public function getCreateBy()
    {
        return $this->create_by;
    }

    /**
     * @param int $create_by
     * @return $this
     */
    public function setCreateBy($create_by)
    {
        $this->create_by = $create_by;

        return $this;
    }

    /**
     * @return int
     */
    public function getUpdateBy()
    {
        return $this->update_by;
    }

    /**
     * @param int $update_by
     * @return $this
     */
    public function setUpdateBy($update_by)
    {
        $this->update_by = $update_by;
        return $this;
    }
}

Form/RestaurantsType.php
<?php

namespace CMS\RestaurantsBundle\Form;

use CMS\GalleryBundle\Form\Types\ImagesType;
use CMS\GeoBundle\Form\Types\GeometryType;
use CMS\LocalizationBundle\Form\Types\LocaleEntityType;
use CMS\LocalizationBundle\Form\Types\LocaleTextareaType;
use CMS\LocalizationBundle\Form\Types\LocaleTextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RestaurantsType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', LocaleTextType::class)
            ->add('city', LocaleEntityType::class, array(
                'class' => 'LocalizationBundle:Cities',
                'property' => 'title',
                'empty_data' => null,
                'placeholder' => '',
            ))
            ->add('address')
            ->add('busy_hours_start')
            ->add('busy_hours_end')
            ->add('days_off', ChoiceType::class, array(
                    'choices' => array(
                        'mon' => 'Monday',
                        'tue' => 'Tuesday',
                        'wed' => 'Wednesday',
                        'thu' => 'Thursday',
                        'fri' => 'Friday',
                        'sat' => 'Saturday',
                        'sun' => 'Sunday',
                    ),
                    'multiple' => true,
                    'expanded' => true
                )
            )
            ->add('kitchens', LocaleEntityType::class, array(
                'class' => 'RestaurantsBundle:Kitchens',
                'property' => 'title',
                'multiple' => true,
                'expanded' => true
            ))
            ->add('descriptions', LocaleTextareaType::class, [
                'required' => false
            ])
            ->add('is_published')
            ->add('is_deleted')
            ->add('photos', ImagesType::class)
            ->add('location', GeometryType::class);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'CMS\RestaurantsBundle\Entity\Restaurants',
            'translation_domain' => 'restaurants'
        ));
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'cms_restaurantsbundle_restaurants';
    }
}

Controller/RestaurantsController.php
<?php

namespace CMS\RestaurantsBundle\Controller;

use CMS\RestaurantsBundle\Entity\Restaurants;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class RestaurantsController
 * @package CMS\RestaurantsBundle\Controller
 */
class RestaurantsController extends Controller
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function listAction()
    {
        $service = $this->get('cms.restaurants.service');

        return $this->render('RestaurantsBundle:Restaurants:list.html.twig', array(
            'restaurants' => $service->findAll()
        ));
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function createAction(Request $request)
    {
        $service = $this->get('cms.restaurants.service');

        $form = $service->generateForm();

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $service->create($form->getData());

                return $this->redirect($this->generateUrl('cms_restaurants_list'));
            }
        }

        return $this->render('RestaurantsBundle:Restaurants:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function editAction(Request $request, $id)
    {
        $service = $this->get('cms.restaurants.service');

        $form = $service->generateForm($service->findOneById($id));

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $service->create($form->getData());

                return $this->redirect($this->generateUrl('cms_restaurants_list'));
            }
        }

        return $this->render('RestaurantsBundle:Restaurants:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction($id)
    {
        $service = $this->get('cms.restaurants.service');

        $service->delete($id);

        return $this->redirect($this->generateUrl('cms_restaurants_list'));
    }
}

Resources/views/Restaurants/edit.html.twig
{% extends 'DashboardBundle:Layout:base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts '@file_uploader'
    'bundles/localization/js/localization_form.js'
    'bundles/restaurants/js/fileuploader.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {% stylesheets
    '@fileupload_css' %}
    <link rel="stylesheet" href="{{ asset_url }}"/>
    {% endstylesheets %}
{% endblock %}

{% block body %}
    {% embed "RestaurantsBundle::main.html.twig" %}
        {% block main %}
            <div class="row">
                {% form_theme form 'RestaurantsBundle::fields.html.twig' %}
                <div class="col-md-12">
                    {{ show_locale_tabs() }}
                    <form method="post" {{ form_enctype(form) }} class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                {{ form_errors(form) }}
                                {{ form_row(form.title,{
                                'label': 'Title'|trans({},'labels'),
                                }) }}
                                {{ form_row(form.address,{
                                'label': 'Address'|trans({},'labels'),
                                }) }}
                                <div class="form-group clearfix">
                                    <label class="required col-sm-2 control-label">{{ 'Busy hours'|trans({}, 'labels') }}
                                        :</label>

                                    <div class="col-md-2 col-sm-2">
                                        {{ form_widget(form.busy_hours_start) }}
                                    </div>
                                    <div class="col-md-2 col-sm-2">
                                        {{ form_widget(form.busy_hours_end) }}
                                    </div>
                                </div>
                                <div class="form-group clearfix">
                                    <label class="required col-sm-2 control-label">{{ 'Days off'|trans({}, 'labels') }}
                                        :</label>

                                    <div class="col-md-10 col-sm-10">
                                        {{ form_widget(form.days_off) }}
                                    </div>
                                </div>
                                {{ form_rest(form) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="well well-sm text-right">
                                    <input type="submit" class="btn btn-primary btn-sm" data-loading-text="Saving..."
                                           value="{{ 'Save'|trans({}, 'systems') }}"/>
                                    <a href="javascript:history.go(-1)"
                                       class="btn btn-default btn-sm">{{ 'Cancel'|trans({}, 'systems') }}</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}

Resources/views/Restaurants/list.html.twig
{% extends 'DashboardBundle:Layout:base.html.twig' %}

{% block body %}
    {% embed 'RestaurantsBundle::main.html.twig' %}
        {% block panelButtons %}
            <a href="{{ url('cms_restaurants_create') }}"
               class="glyphicon glyphicon-plus btn btn-success btn-xs">{{ 'Add'|trans }}</a>
        {% endblock %}

        {% block main %}
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <th><input type="checkbox" data-action="selectAll"/></th>
                    <th>ID</th>
                    <th>{{ 'Title'|trans }}</th>
                    <th>{{ 'Status'|trans }}</th>
                    <th>{{ 'Create by'|trans }}</th>
                    <th>{{ 'Date'|trans }}</th>
                    <th></th>
                    <th></th>
                    </thead>
                    <tbody>
                    {% for restaurant in restaurants %}
                        <tr>
                            <td><input type="checkbox" value="{{ restaurant.id }}" name="mark[]"/></td>
                            <td>{{ restaurant.id }}</td>
                            <td>
                                <a href="{{ url('cms_restaurants_edit', {id: restaurant.id}) }}">
                                    {{ restaurant.title|locale }}
                                </a>
                            </td>
                            <td></td>
                            <td>{{ restaurant.createBy }}</td>
                            <td>{{ restaurant.dateCreate|date('d.m.Y') }}</td>
                            <td><a href='{{ url('cms_restaurants_edit', {id: restaurant.id}) }}'><span
                                            class="glyphicon lead text-primary glyphicon-pencil"></span></a></td>
                            <td><a href='{{ url('cms_restaurants_delete', {id: restaurant.id}) }}'><span
                                            class="glyphicon lead text-danger glyphicon-remove-circle"></span></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}